---
spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://mongosrvdev:ZxuF9TxpDae5dGT@pre-prod.gngtd.gcp.mongodb.net/dev?retryWrites=true&w=majority}
springdoc:
  swagger-ui:
    path: /budgets/swagger-ui.html
  api-docs:
    path: /budgets/v3/api-docs
budget:
  recreate: "0 59 23 28 * ?"